import { z } from 'zod';
export const CreateKaryawanSchema = z.object({
  id: z.number().optional(), // Auto-increment field, so it can be optional
  agama_id: z.number().nullable().optional(),
  statuskerja_id: z.number().nullable().optional(),
  npwp: z.string().max(30).nullable().optional(),
  statuskaryawan_id: z.number().nullable().optional(),
  jumlahtanggungan: z.number().nullable().optional(),
  noktp: z.string().max(16).nullable().optional(),
  namakaryawan: z.string().nullable().optional(),
  namaalias: z.string().nullable().optional(),
  jeniskelamin_rid: z.number().nullable().optional(),
  alamat: z.string().nullable().optional(),
  tempatlahir: z.string().nullable().optional(),
  tgllahir: z.date().nullable().optional(),
  golongandarah_id: z.number().nullable().optional(),
  nohp: z.string().nullable().optional(),
  foto: z.any().nullable().optional(),
  tglmasukkerja: z.date().nullable().optional(),
  cabang_id: z.number().nullable().optional(),
  jabatan_id: z.number().nullable().optional(),
  keterangan: z.string().nullable().optional(),
  namaibu: z.string().nullable().optional(),
  namaayah: z.string().nullable().optional(),
  pengalamankerja: z.string().nullable().optional(),
  kodekaryawan: z.string().max(200).nullable().optional(),
  email: z.string().email().nullable().optional(),
  tglresign: z.date().nullable().optional(),
  tglmutasi: z.date().nullable().optional(),
  atasan_id: z.number().nullable().optional(),
  thr_id: z.number().nullable().optional(),
  daftaremail_id: z.number().nullable().optional(),
  kodemarketing: z.string().max(100).nullable().optional(),
  alasanberhenti: z.string().nullable().optional(),
  absen_id: z.number().nullable().optional(),
  spesifikasikomputer: z.string().nullable().optional(),
  approval_id: z.number().nullable().optional(),
  statusaktif: z.number().nullable().optional(),
  info: z.string().nullable().optional(),
  modifiedby: z.string().max(200).nullable().optional(),
  created_at: z.date().nullable().optional(),
  updated_at: z.date().nullable().optional(),
  filters: z.any().nullable().optional(),
});

export type CreateKaryawanDto = z.infer<typeof CreateKaryawanSchema>;
